//! Route handlers for /logs.

use crate::routes::render_page;
use crate::state::AppState;

pub fn index(state: &AppState) -> String {
    let rows = state
        .events()
        .iter()
        .map(|event| {
            format!(
                "<tr><td>{}</td><td class=\"{}\">{}</td><td>{}</td></tr>",
                event.timestamp,
                event.severity.class_name(),
                event.severity.label(),
                event.message
            )
        })
        .collect::<Vec<_>>()
        .join("");

    let body = format!(
        r#"<section class="panel">
  <h2>Security event log</h2>
  <p class="muted" style="margin-top:10px;">Recent network decisions generated by the IP validation pipeline.</p>
  <table>
    <thead><tr><th>Time</th><th>Severity</th><th>Event</th></tr></thead>
    <tbody>{}</tbody>
  </table>
</section>"#,
        rows
    );

    render_page("AegisOS Security Logs", "/logs", body)
}
