//! DHCP/DNS router backend for aegisd.

use std::fs;
use std::process::Command;
use crate::network::{self, RouterConfig};

const DNSMASQ_CONFIG_PATH: &str = "/etc/dnsmasq.d/aegisos-router.conf";

pub fn status() -> String {
    let dnsmasq = network::command_available("dnsmasq");
    let config_present = fs::metadata(DNSMASQ_CONFIG_PATH).is_ok();
    let active = Command::new("systemctl")
        .args(["is-active", "--quiet", "dnsmasq"])
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    format!(
        r#"{{"dns":{{"backend":"dnsmasq","available":{},"active":{},"config_present":{},"config_path":"{}"}}}}"#,
        dnsmasq,
        active,
        config_present,
        DNSMASQ_CONFIG_PATH,
    )
}

pub fn write_dnsmasq_config() -> String {
    let cfg = RouterConfig::load();
    let content = format!(
        "# Generated by AegisOS first-boot/router provisioning\n\
interface={}\n\
bind-interfaces\n\
domain-needed\n\
bogus-priv\n\
no-resolv\n\
server=1.1.1.1\n\
server=9.9.9.9\n\
dhcp-range={},{} ,12h\n\
dhcp-option=option:router,{}\n\
dhcp-option=option:dns-server,{}\n",
        cfg.lan,
        cfg.dhcp_start,
        cfg.dhcp_end,
        cfg.lan_gateway,
        cfg.dns_listen,
    ).replace(" ,", ",");

    if network::dry_run() {
        return format!(r#"{{"dnsmasq_config":{{"ok":true,"dry_run":true,"path":"{}"}}}}"#, DNSMASQ_CONFIG_PATH);
    }

    if let Err(e) = fs::create_dir_all("/etc/dnsmasq.d") {
        return format!(r#"{{"dnsmasq_config":{{"ok":false,"error":"{}"}}}}"#, network::json_escape(&e.to_string()));
    }
    match fs::write(DNSMASQ_CONFIG_PATH, content) {
        Ok(_) => {
            let _ = Command::new("systemctl").args(["restart", "dnsmasq"]).status();
            format!(r#"{{"dnsmasq_config":{{"ok":true,"path":"{}"}}}}"#, DNSMASQ_CONFIG_PATH)
        }
        Err(e) => format!(r#"{{"dnsmasq_config":{{"ok":false,"error":"{}"}}}}"#, network::json_escape(&e.to_string())),
    }
}
