//! DHCP/DNS router backend for aegisd.
//!
//! AegisOS runs dnsmasq as a service-manager child. The daemon writes and
//! validates the configuration directly; it does not depend on host systemd.

use std::fs;
use std::path::Path;
use std::process::{Command, Stdio};

use crate::network::{self, RouterConfig};

const DEFAULT_CONFIG_PATH: &str = "/etc/dnsmasq.d/aegisos-router.conf";
const DEFAULT_PID_PATH: &str = "/run/aegisos-router/dnsmasq.pid";
const DEFAULT_FILTER_UPSTREAM: &str = "127.0.0.1#53530";

pub fn status() -> String {
    let config_path = config_path();
    let pid_path = pid_path();
    let dnsmasq = network::command_available("dnsmasq");
    let config_present = fs::metadata(&config_path).is_ok();
    let config_valid = dnsmasq && config_present && validate_config(&config_path);
    let pid = read_pid(&pid_path);
    let active = pid.map(process_exists).unwrap_or(false);

    format!(
        r#"{{"dns":{{"backend":"dnsmasq","available":{},"active":{},"pid":{},"config_present":{},"config_valid":{},"config_path":"{}","pid_path":"{}"}}}}"#,
        dnsmasq,
        active,
        pid.map(|value| value.to_string())
            .unwrap_or_else(|| "null".to_owned()),
        config_present,
        config_valid,
        network::json_escape(&config_path),
        network::json_escape(&pid_path),
    )
}

pub fn write_dnsmasq_config() -> String {
    let cfg = RouterConfig::load();
    let config_path = config_path();
    let pid_path = pid_path();
    let filter_upstream = std::env::var("AEGIS_DNSMASQ_UPSTREAM")
        .unwrap_or_else(|_| DEFAULT_FILTER_UPSTREAM.to_owned());
    let content = format!(
        "# Generated by AegisOS router provisioning\n\
interface={}\n\
bind-dynamic\n\
listen-address={}\n\
domain-needed\n\
bogus-priv\n\
no-resolv\n\
server={}\n\
dhcp-authoritative\n\
dhcp-range={},{},12h\n\
dhcp-option=option:router,{}\n\
dhcp-option=option:dns-server,{}\n\
pid-file={}\n",
        cfg.lan,
        cfg.dns_listen,
        filter_upstream,
        cfg.dhcp_start,
        cfg.dhcp_end,
        cfg.lan_gateway,
        cfg.dns_listen,
        pid_path,
    );

    if network::dry_run() {
        return format!(
            r#"{{"dnsmasq_config":{{"ok":true,"dry_run":true,"path":"{}","bytes":{}}}}}"#,
            network::json_escape(&config_path),
            content.len()
        );
    }

    let Some(parent) = Path::new(&config_path).parent() else {
        return r#"{"dnsmasq_config":{"ok":false,"error":"invalid config path"}}"#
            .to_owned();
    };
    if let Err(error) = fs::create_dir_all(parent) {
        return error_json(&config_path, &error.to_string());
    }
    if let Some(parent) = Path::new(&pid_path).parent() {
        if let Err(error) = fs::create_dir_all(parent) {
            return error_json(&config_path, &error.to_string());
        }
    }

    if let Err(error) = fs::write(&config_path, content) {
        return error_json(&config_path, &error.to_string());
    }

    if !validate_config(&config_path) {
        return error_json(&config_path, "dnsmasq rejected generated configuration");
    }

    let reloaded = read_pid(&pid_path)
        .filter(|pid| process_exists(*pid))
        .map(signal_reload)
        .unwrap_or(false);
    format!(
        r#"{{"dnsmasq_config":{{"ok":true,"path":"{}","validated":true,"reloaded":{}}}}}"#,
        network::json_escape(&config_path),
        reloaded
    )
}

fn config_path() -> String {
    std::env::var("AEGISOS_DNSMASQ_CONFIG")
        .unwrap_or_else(|_| DEFAULT_CONFIG_PATH.to_owned())
}

fn pid_path() -> String {
    std::env::var("AEGISOS_DNSMASQ_PID")
        .unwrap_or_else(|_| DEFAULT_PID_PATH.to_owned())
}

fn validate_config(path: &str) -> bool {
    Command::new("dnsmasq")
        .arg("--test")
        .arg(format!("--conf-file={path}"))
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|status| status.success())
        .unwrap_or(false)
}

fn read_pid(path: &str) -> Option<u32> {
    fs::read_to_string(path).ok()?.trim().parse().ok()
}

fn process_exists(pid: u32) -> bool {
    Path::new(&format!("/proc/{pid}")).exists()
}

fn signal_reload(pid: u32) -> bool {
    Command::new("kill")
        .args(["-HUP", &pid.to_string()])
        .status()
        .map(|status| status.success())
        .unwrap_or(false)
}

fn error_json(path: &str, error: &str) -> String {
    format!(
        r#"{{"dnsmasq_config":{{"ok":false,"path":"{}","error":"{}"}}}}"#,
        network::json_escape(path),
        network::json_escape(error)
    )
}
